### ISSUE TITLE
Code analysis' producement: "Make "replacements" "readonly" at the required placements.

### ISSUE THREAD

**Issue by azollai** [Zayyy01/wax#1]

**Comment by azollai** [comment]
![18053048_1370140389675128_749214827_o](https://cloud.githubusercontent.com/assets/17653516/25195705/c0131a70-253e-11e7-8948-7c0bcf9d5dfe.png)
![18049813_1431926536830828_7067697_o](https://cloud.githubusercontent.com/assets/17653516/25195706/c122f7a0-253e-11e7-9018-117316cb64d9.jpg)

**Comment by Zayyy01** [comment]
The commit [https://github.com/Zayyy01/wax/commit/bcc92b64c33a5424ce1418a37122243913b9c12a](https://github.com/Zayyy01/wax/commit/bcc92b64c33a5424ce1418a37122243913b9c12a) solved this issue.

**Comment by azollai** [comment]
Nice perception,excelent work.

**Comment by micskeiz** [comment]
OK
