### ISSUE TITLE
Code analysis: potential system.NullReferenceException at class UnwrapVisitor.

### ISSUE THREAD

**Issue by Zayyy01** [Zayyy01/wax#2]
Resharper's code inspection showed a code quality issue at the file `UnwrapVisitor.cs`: using  the `field` variable may throw a System.NullReferenceException.
![image](https://cloud.githubusercontent.com/assets/17637335/25221858/e3a7e52e-25b6-11e7-8267-11c3729e63c7.png)

**Comment by azollai** [comment]
I have absolved this issue. I also repaired every issue, that Resharper has recommended.
![hazi1](https://cloud.githubusercontent.com/assets/17653516/25222193/1150ae06-25b8-11e7-8d5e-b2f0e746078a.JPG)

**Comment by azollai** [comment]
Here is the commit link:
https://github.com/Zayyy01/wax/commit/bcc92b64c33a5424ce1418a37122243913b9c12a
I committed directly to master branch.

**Comment by Zayyy01** [comment]
Ok. This commit also solves the #1 (make the variable readonly) issue.
