### ISSUE TITLE
CI beüzemelése

### ISSUE THREAD

**Issue by KarpatiAttila** [Zayyy01/wax#3]
CI beüzemelése.

**Comment by Viktoria95** [comment]
Sikeres volt.

**Comment by KarpatiAttila** [comment]
![image](https://cloud.githubusercontent.com/assets/17654532/25223741/90cce29a-25bc-11e7-8b89-480510f31df8.png)

**Comment by micskeiz** [comment]
OK. 

Next time please link the respective commit or pull request to the issues.
