### ISSUE TITLE
Unit tests needed

### ISSUE THREAD

**Issue by Zayyy01** [Zayyy01/wax#5]
@KarpatiAttila, @Viktoria95 please write some tests for the project.

**Comment by Viktoria95** [comment]
Done.

**Comment by Viktoria95** [comment]
![image](https://cloud.githubusercontent.com/assets/17654597/25713969/cafa32ca-30f6-11e7-8033-c98b20e060d0.png)

**Comment by Viktoria95** [comment]
e7e926ffff0ee36835154d947c34f1d7e28bbf5c

**Comment by KarpatiAttila** [comment]
A tesztek sikeresen lefutottak. 
Kapcsolódó wiki oldal: [UnitTests](https://github.com/Zayyy01/wax/wiki/Unit-Tests)
