### ISSUE TITLE
ReSharper Unit test coverage

### ISSUE THREAD

**Issue by azollai** [Zayyy01/wax#6]
I have tested unit tests with ReSharper made by Attila and Viktóra. The coverage seemed to be perfect. I  implemented a test for the Constant method in order to increase the measure of coverage.
Please show the Unit test coverage of the Project before and after my action by ReSharper.

**Comment by Zayyy01** [comment]
The code coverity status before your unit test:
![coverity-before](https://cloud.githubusercontent.com/assets/17637335/25697339/deed9b5a-30ba-11e7-9621-27f320c7b189.PNG)

**Comment by Zayyy01** [comment]
After your addition, the code coverity percent is increased:
![coverity-after](https://cloud.githubusercontent.com/assets/17637335/25697547/a97c9f24-30bb-11e7-9412-a51c3a68d6e7.PNG)
I close this issue, and make a wiki page where Code coverity results will be avaible.

**Comment by Zayyy01** [comment]
You can find [here](https://github.com/Zayyy01/wax/wiki/Code-Coverity) the wiki page about this topic.
